import Head from 'next/head'
import { CircularEconomyReport } from '../../components/CircularEconomyReport'

export default function CircularEconomyReports () {
  const circularEconomyReportNames = [
    {
      title: 'Primer reporte de Economía Circular',
      titleReportLink: 'Primer reporte',
      reportLink: '#',
      presentationLink: '#',
      attachmentsLink: '#',
      webinarLink: '#',
      srcImage: '/primer-reporte.jpg',
      date: new Date(2020, 8, 5)
    },
    {
      title: 'Segundo reporte de Economía Circular',
      titleReportLink: 'Segundo reporte',
      reportLink: '#',
      presentationLink: '#',
      attachmentsLink: '#',
      webinarLink: '#',
      srcImage: '/segundo-reporte.jpg',
      date: new Date(2020, 12, 11)
    },
    {
      title: 'Tercer reporte de Economía Circular',
      titleReportLink: 'Tercer reporte',
      reportLink: '#',
      presentationLink: '#',
      attachmentsLink: '#',
      webinarLink: '#',
      srcImage: '/tercer-reporte.jpg',
      date: new Date(2021, 7, 28)
    },
    {
      title: 'Cuarto reporte de Economía Circular',
      titleReportLink: 'Cuarto reporte',
      reportLink: '#',
      presentationLink: '#',
      attachmentsLink: '#',
      webinarLink: '#',
      srcImage: '/cuarto-reporte.jpg',
      date: new Date(2021, 12, 2)
    }
  ]
  return (
        <>
            <Head>
                <title>Reportes de Economía Circular | DANE</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='py-12 lg:py-16 xl:py-20'>
                <div className='mx-auto w-10/12 max-w-screen-lim'>
                    <div className='flex flex-col lg:flex-row lg:justify-between lg:items-center gap-y-8'>
                        <div className='lg:w-5/12'>
                            <div className='space-y-[42px]'>
                                <h2 className='text-blue-ocean text-2xl 2xl:text-[32px]'>
                                    <span className='font-bold'>Reportes </span>
                                    de Economía Circular
                                </h2>
                                <div className='space-y-[22px]'>
                                    <p>
                                        Buscan aportar información oportuna para la toma de decisiones y el fortalecimiento de la política pública en materia de Economía Circular.
                                    </p>
                                    <p>
                                        Los Reportes de Economía Circular son el resultado de los esfuerzos de articulación estadística que ha emprendido el DANE al interior de sus Direcciones Técnicas, pero también en el contexto del Sistema Estadístico Nacional - SEN.
                                    </p>
                                    <p>
                                        A la fecha el DANE ha publicado 4 reportes de Economía Circular con la participación de indicadores del IDEAM, Invemar y el DANE.
                                    </p>
                                </div>
                            </div>
                        </div>
                        <div className='lg:w-6/12'>
                            <CircularEconomyReport item={circularEconomyReportNames[circularEconomyReportNames.length - 1]} isLastReport={true} />
                        </div>
                    </div>
                </div>
            </div>

            <div className='py-12 lg:py-16 xl:py-20'>
                <div className='mx-auto w-10/12 max-w-screen-lim'>
                    <div className='space-y-[49px]'>
                        <div className='text-center'>
                            <h3 className='font-bold text-xl xl:text-2xl text-blue-dark'>
                                Información histórica de reportes
                            </h3>
                        </div>
                        <div className='grid grid-cols-1 lg:grid-cols-2 xl:gap-x-[52px] gap-y-8 gap-x-10 xl:gap-y-[42px]'>
                            {
                                circularEconomyReportNames.map((item, index) => <CircularEconomyReport key={`report-${index + 1}`} item={item} />)
                            }
                        </div>
                        <div className='flex justify-end'>
                            <div className='bg-blue-ocean bg-opacity-[0.18] p-4 pr-6 lg:py-[21px] lg:px-[37px] rounded-tr-[40px] overflow-hidden w-[155px] lg:w-[261px]'>
                                <img className='mx-auto' src='/logo-datasketch.svg' alt='logo datasketch' />
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
  )
}
