import Head from 'next/head'
import { CircularEconomyReport } from '../../components/CircularEconomyReport'
import data from '../../data/reports.json'

export async function getStaticProps () {
  return {
    props: { reports: data } // will be passed to the page component as props
  }
}

export default function CircularEconomyReports ({ reports }) {
  return (
    <>
      <Head>
        <title>Reportes de Economía Circular | DANE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className='py-12 lg:py-16 xl:py-20'>
        <div className='mx-auto w-10/12 max-w-screen-lim'>
          <div className='flex flex-col lg:flex-row lg:justify-between lg:items-center gap-y-8'>
            <div className='lg:w-5/12'>
              <div className='space-y-[42px]'>
                <h2 className='text-blue-ocean text-2xl 2xl:text-[32px]'>
                  <span className='font-bold'>Reportes </span>
                  de Economía Circular
                </h2>
                <div className='space-y-[22px]'>
                  <p>
                    Buscan aportar información oportuna para la toma de decisiones y el fortalecimiento de la política pública en materia de Economía Circular.
                  </p>
                  <p>
                    Los Reportes de Economía Circular son el resultado de los esfuerzos de articulación estadística que ha emprendido el DANE con las demás entidades del Sistema Estadístico Nacional - SEN para identificar, fortalecer y publicar información relevante sobre Economía Circular.
                  </p>
                  <p>
                    A la fecha el DANE ha publicado 5 reportes de Economía Circular con la participación de indicadores del IDEAM, Invemar y el DANE.
                  </p>
                </div>
              </div>
            </div>
            <div className='lg:w-6/12'>
              <CircularEconomyReport item={reports[reports.length - 1]} isLastReport={true} showLinkButton={true} />
            </div>
          </div>
        </div>
      </div>

      <div className='py-12 lg:py-16 xl:py-20'>
        <div className='mx-auto w-10/12 max-w-screen-lim'>
          <div className='space-y-[49px]'>
            <div className='text-center'>
              <h3 className='font-bold text-xl xl:text-2xl text-blue-dark'>
                Información histórica de reportes
              </h3>
            </div>
            <div className='grid grid-cols-1 lg:grid-cols-2 xl:gap-x-[52px] gap-y-8 gap-x-10 xl:gap-y-[42px]'>
              {
                reports.slice(0, reports.length - 1).reverse().map((item, index) => <CircularEconomyReport key={`report-${index + 1}`} item={item} showLinkButton={index === 0} />)
              }
            </div>
          </div>
        </div>
      </div>

      <div className='py-12'>
        <div className='mx-auto w-10/12 max-w-screen-lim'>
          <div className='flex justify-center lg:justify-between items-center flex-wrap gap-x-12 gap-y-8'>
              <div>
                <img className='h-20' src='/images/MINAMBIENTE_logo.jpg' alt='minambiente logo' />
              </div>
              <div>
                <img className='h-20' src='/images/DANE_logo.png' alt='dane logo' />
              </div>
              <div>
                <img className='h-20' src='/images/IDEAM_logo.png' alt='ideam logo' />
              </div>
              <div>
                <img className='h-20' src='/images/INVEMAR_logo.png' alt='invemar logo' />
              </div>
          </div>
        </div>
      </div>
    </>
  )
}
