import Head from 'next/head'

export default function Home () {
  return (
    <>
      <Head>
        <title>Economía circular | DANE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p className='text-3xl'>Hola mundo</p>
    </>
  )
}
